[workspace]
members = [
    "crates/mcp-core",
    "crates/mcp-transport", 
    "crates/mcp-server",
    "examples/filesystem-server",
    "examples/image-generation-server",
    "examples/blog-generation-server",
    "examples/creative-content-server"
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["MCP Boilerplate Contributors"]
license = "MIT"
repository = "https://github.com/netadx1ai/mcp-boilerplate-rust"
homepage = "https://github.com/netadx1ai/mcp-boilerplate-rust"
documentation = "https://docs.rs/mcp-boilerplate-rust"
keywords = ["mcp", "protocol", "ai", "tools", "server"]
categories = ["network-programming", "api-bindings", "web-programming"]

[workspace.dependencies]
# Core dependencies
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"
thiserror = "1.0"

# Async and networking
axum = "0.7"
tower = "0.4"
tower-http = { version = "0.5", features = ["trace", "cors"] }
hyper = "1.0"
tokio-util = { version = "0.7", features = ["io"] }

# Logging and tracing
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# CLI and utilities
clap = { version = "4.0", features = ["derive"] }
uuid = { version = "1.0", features = ["v4", "serde"] }
async-trait = "0.1"

# Testing and development
rstest = "0.18"
tokio-test = "0.4"

[profile.dev]
opt-level = 0
debug = true
panic = "unwind"

[profile.release]
opt-level = 3
debug = false
panic = "abort"
lto = true
codegen-units = 1

[profile.test]
opt-level = 1
debug = true